// Option lists for the Plant Builder "New Plant" form. Values MUST match the
// backend mirror at certification_backend/src/modules/plants/plants.constants.ts

export type Option = { value: string; label: string };

export const PRIMARY_PATHWAYS: Option[] = [
  { value: "synthetic", label: "Synthetic Pathway" },
  { value: "biogenic", label: "Biogenic Pathway" },
  { value: "thermochemical", label: "Thermochemical Pathway" },
  { value: "hybrid", label: "Hybrid Pathway" },
  { value: "physical_recovery", label: "Physical Recovery Pathway" },
  { value: "other", label: "Other" },
];

export const PLANT_CONFIGURATIONS: Option[] = [
  { value: "new_build", label: "New Build" },
  { value: "retrofit", label: "Retrofit" },
  { value: "expansion", label: "Expansion" },
  { value: "mixed", label: "Mixed" },
];

export const SITE_ENVIRONMENTS: Option[] = [
  { value: "coastal", label: "Coastal" },
  { value: "inland", label: "Inland" },
  { value: "industrial_cluster", label: "Industrial Cluster" },
  { value: "port_terminal", label: "Port Terminal" },
  { value: "urban", label: "Urban" },
  { value: "rural", label: "Rural" },
  { value: "other", label: "Other" },
];

export const MATURITY_STAGES: Option[] = [
  { value: "concept", label: "Concept" },
  { value: "pre_feasibility", label: "Pre Feasibility" },
  { value: "feasibility", label: "Feasibility" },
  { value: "pre_feed", label: "Pre FEED" },
  { value: "feed", label: "FEED" },
  { value: "permitting", label: "Permitting" },
  { value: "pre_fid", label: "Pre FID" },
  { value: "fid", label: "FID" },
  { value: "construction", label: "Construction" },
  { value: "commissioning", label: "Commissioning" },
  { value: "operating", label: "Operating" },
];

export const CERTIFICATION_PHASES: Option[] = [
  { value: "not_started", label: "Not Started" },
  { value: "eligibility", label: "Eligibility" },
  { value: "scoping", label: "Scoping" },
  { value: "data_collection", label: "Data Collection" },
  { value: "pre_assessment", label: "Pre Assessment" },
  { value: "documentation_prepared", label: "Documentation Prepared" },
  { value: "auditor_engagement", label: "Auditor Engagement" },
  { value: "certification_submitted", label: "Certification Submitted" },
  { value: "certified", label: "Certified" },
  { value: "surveillance", label: "Surveillance" },
];

export const FUEL_TYPES: Option[] = [
  { value: "hydrogen", label: "Hydrogen" },
  { value: "ammonia", label: "Ammonia" },
  { value: "methanol", label: "Methanol" },
  { value: "methane", label: "Methane" },
  { value: "diesel", label: "Diesel" },
  { value: "kerosene", label: "Kerosene" },
  { value: "naphtha", label: "Naphtha" },
  { value: "butane", label: "Butane" },
  { value: "propane", label: "Propane" },
  { value: "ethanol", label: "Ethanol" },
  { value: "gasoline", label: "Gasoline" },
];

export const CAPACITY_UNITS: Option[] = [
  { value: "ton_per_year", label: "Ton per Year" },
  { value: "ton_per_day", label: "Ton per Day" },
  { value: "kilogram_per_hour", label: "Kilogram per Hour" },
  { value: "normal_cubic_meter_per_hour", label: "Normal Cubic Meter per Hour" },
];

export const COUNTRIES: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
