import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// Components
import Sidebar from "@/components/ui/Sidebar";
import Navbar from "@/components/ui/Navbar";

// Data
import notificationsData from "../data/notificationsData.json";

// Font Configurations
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Sidebar and Navbar */}
        <div className="flex w-full h-full bg-blue-50">
          <Sidebar />
          <div className="flex flex-col w-full p-6">
            <Navbar
              notifications={notificationsData}
              userName="Ramadan"
            />
            {children}
            
          </div>
        </div>
      </body>
    </html>
  );
}
